import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../../components/Header'
import { Footer } from '../../components/Footer'
import { PDFUpload } from '../../components/PDFUpload'
import { ConversionProgress } from '../../components/ConversionProgress'
import { VideoPreview } from '../../components/VideoPreview'
import { ProcessingAnimation } from '../../components/animations/ProcessingAnimation'
import { ContentPreview } from '../../components/ContentPreview'
import { RemotionPlayer } from '../../components/RemotionPlayer'
import { PDFConversionController } from '../../controllers/PDFConversionController'
import { PDFFile, ConversionOptions, ConversionStatus, PDFExtractionResponse } from '../../models/Conversion'
import { Settings, Play, CheckCircle } from 'lucide-react'
import { MotionWrapper } from '../../components/ui/MotionWrapper'

type ProcessStage = 'uploading' | 'extracting' | 'processing' | null

const ConvertPDFToVideo: NextPage = () => {
  const [selectedFile, setSelectedFile] = useState<PDFFile | null>(null)
  const [jobId, setJobId] = useState<string | null>(null)
  const [isUploading, setIsUploading] = useState(false)
  const [isConverting, setIsConverting] = useState(false)
  const [processingStage, setProcessingStage] = useState<ProcessStage>(null)
  const [processingProgress, setProcessingProgress] = useState(0)
  const [conversionStatus, setConversionStatus] = useState<ConversionStatus | null>(null)
  const [showOptions, setShowOptions] = useState(false)
  const [options, setOptions] = useState<ConversionOptions>({
    voiceId: 'en',  // gTTS language code
    videoQuality: 'high',
    includeAnimations: true,
    includeTransitions: true,
  })
  const [error, setError] = useState<string | null>(null)

  // Content preview state
  const [extractedContent, setExtractedContent] = useState<PDFExtractionResponse | null>(null)
  const [showPreview, setShowPreview] = useState(false)
  const [videoReady, setVideoReady] = useState(false)

  const handleFileSelect = (file: PDFFile) => {
    setSelectedFile(file)
    setError(null)
  }

  const handleUpload = async () => {
    if (!selectedFile?.file) {
      setError('Please select a PDF file')
      return
    }

    try {
      setIsUploading(true)
      setError(null)

      // Stage 1: Uploading
      setProcessingStage('uploading')
      setProcessingProgress(10)

      const response = await PDFConversionController.uploadPDF(selectedFile.file)
      setJobId(response.jobId)

      setProcessingProgress(40)

      // Stage 2: Extracting
      setProcessingStage('extracting')
      setProcessingProgress(50)

      // Extract content
      const extraction = await PDFConversionController.extractContent(response.jobId)

      setProcessingProgress(100)

      // Store extraction and show preview
      setExtractedContent(extraction)

      // Clear processing state and show preview
      setTimeout(() => {
        setProcessingStage(null)
        setProcessingProgress(0)
        setShowPreview(true)  // Show content preview
      }, 500)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to upload PDF')
      setProcessingStage(null)
      setProcessingProgress(0)
    } finally {
      setIsUploading(false)
    }
  }

  const handleStartGeneration = async () => {
    // Scripts, images, and audio are already generated by ContentPreview
    // Just show the video player
    setShowPreview(false)
    setVideoReady(true)
  }

  const handleConvert = async () => {
    if (!jobId) {
      setError('Please upload a PDF first')
      return
    }

    try {
      console.log('Starting conversion with jobId:', jobId, 'options:', options)
      setIsConverting(true)
      setError(null)

      const result = await PDFConversionController.startConversion(jobId, options)
      console.log('Conversion started:', result)
    } catch (err) {
      console.error('Conversion error:', err)
      setError(err instanceof Error ? err.message : 'Failed to start conversion')
      setIsConverting(false)
    }
  }

  const handleConversionComplete = (status: ConversionStatus) => {
    setConversionStatus(status)
    setIsConverting(false)
  }

  const handleConversionError = (errorMessage: string) => {
    setError(errorMessage)
    setIsConverting(false)
  }

  return (
    <>
      <Head>
        <title>Convert PDF to Video - AI Study Companion</title>
        <meta name="description" content="Convert your PDF documents into engaging video lectures with AI narration" />
      </Head>

      <div className="min-h-screen bg-gray-50">
        <Header />

        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl py-8 sm:py-12">
          <MotionWrapper
            as="div"
            className="text-center mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
              Convert PDF to Video
            </h1>
            <p className="text-lg text-gray-600">
              Transform your PDF documents into engaging video lectures
            </p>
          </MotionWrapper>

          {/* Upload Section */}
          {!jobId && (
            <div className="space-y-6">
              <PDFUpload onFileSelect={handleFileSelect} />

              {/* Conversion Options */}
              <MotionWrapper
                as="div"
                className="bg-white rounded-xl p-6 shadow-lg"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: 0.1 }}
              >
                <button
                  onClick={() => setShowOptions(!showOptions)}
                  className="flex items-center justify-between w-full text-left"
                >
                  <div className="flex items-center gap-2">
                    <Settings size={20} className="text-gray-600" />
                    <h3 className="text-lg font-semibold text-gray-900">Conversion Options</h3>
                  </div>
                  <span className="text-sm text-gray-500">{showOptions ? 'Hide' : 'Show'}</span>
                </button>

                {showOptions && (
                  <div className="mt-4 space-y-4 pt-4 border-t border-gray-200">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Voice
                        </label>
                        <select
                          value={options.voiceId}
                          onChange={(e) => setOptions({ ...options, voiceId: e.target.value })}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        >
                          <option value="en">English (US)</option>
                          <option value="en-uk">English (UK)</option>
                          <option value="en-au">English (Australia)</option>
                          <option value="en-in">English (India)</option>
                        </select>
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Video Quality
                        </label>
                        <select
                          value={options.videoQuality}
                          onChange={(e) =>
                            setOptions({
                              ...options,
                              videoQuality: e.target.value as 'low' | 'medium' | 'high',
                            })
                          }
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        >
                          <option value="high">High</option>
                          <option value="medium">Medium</option>
                          <option value="low">Low</option>
                        </select>
                      </div>
                    </div>

                    <div className="flex items-center gap-4">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={options.includeAnimations}
                          onChange={(e) =>
                            setOptions({ ...options, includeAnimations: e.target.checked })
                          }
                          className="rounded"
                        />
                        <span className="text-sm text-gray-700">Animations</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={options.includeTransitions}
                          onChange={(e) =>
                            setOptions({ ...options, includeTransitions: e.target.checked })
                          }
                          className="rounded"
                        />
                        <span className="text-sm text-gray-700">Transitions</span>
                      </label>
                    </div>
                  </div>
                )}
              </MotionWrapper>

              {/* Upload Button */}
              {selectedFile && !isUploading && (
                <MotionWrapper
                  as="button"
                  onClick={handleUpload}
                  disabled={isUploading}
                  className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors font-semibold text-lg flex items-center justify-center gap-2"
                  whileHover={{ scale: isUploading ? 1 : 1.02 }}
                  whileTap={{ scale: isUploading ? 1 : 0.98 }}
                >
                  <Play size={20} />
                  Upload & Start Conversion
                </MotionWrapper>
              )}

              {/* Processing Animation */}
              {isUploading && processingStage && (
                <ProcessingAnimation
                  stage={processingStage}
                  progress={processingProgress}
                  fileName={selectedFile?.file?.name}
                />
              )}

              {error && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-600">
                  {error}
                </div>
              )}
            </div>
          )}

          {/* Content Preview - Show after extraction */}
          {showPreview && extractedContent && jobId && (
            <MotionWrapper
              as="div"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
            >
              <ContentPreview
                pages={extractedContent.pages}
                totalPages={extractedContent.totalPages}
                jobId={jobId}
                onGenerate={handleStartGeneration}
                onCancel={() => {
                  setShowPreview(false)
                  setExtractedContent(null)
                }}
              />
            </MotionWrapper>
          )}

          {/* Remotion Video Player - Show when video is ready */}
          {videoReady && jobId && (
            <MotionWrapper
              as="div"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
            >
              <RemotionPlayer jobId={jobId} />
            </MotionWrapper>
          )}

          {/* Conversion Progress */}
          {jobId && isConverting && (
            <ConversionProgress
              jobId={jobId}
              onComplete={handleConversionComplete}
              onError={handleConversionError}
            />
          )}

          {/* Start Conversion Button (after upload) */}
          {jobId && !isConverting && !conversionStatus && (
            <div className="space-y-4">
              {/* Success message showing file is ready */}
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-center gap-2 text-green-700">
                  <CheckCircle size={20} />
                  <div>
                    <p className="font-semibold">PDF Uploaded Successfully!</p>
                    <p className="text-sm text-green-600">
                      File ready for conversion. Click below to start.
                    </p>
                  </div>
                </div>
              </div>

              <MotionWrapper
                as="button"
                type="button"
                onClick={(e: React.MouseEvent) => {
                  e.preventDefault()
                  handleConvert()
                }}
                className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-semibold text-lg flex items-center justify-center gap-2"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                <Play size={20} />
                Start Video Conversion
              </MotionWrapper>
            </div>
          )}

          {/* Video Preview */}
          {conversionStatus?.status === 'completed' && jobId && (
            <div className="mt-8">
              <VideoPreview jobId={jobId} />
            </div>
          )}
        </div >

        <Footer />
      </div >
    </>
  )
}

export default ConvertPDFToVideo

